"use client"
import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Image from 'next/image';
import { Home, BookOpen, User, LogIn, Newspaper } from 'lucide-react';
import { Button } from '../../components/ui/button';
import { usePathname, useRouter } from "next/navigation";
import Footer from "~/components/footer";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

function TopNav() {
  const logoUrl = "https://velgg90lgs.ufs.sh/f/ymmBhW7qEDZCbpaNxYJTjwQiehyaprgucNE83TskxCXJonmI"

  return (
    <nav className="flex items-center justify-between w-full p-4 text-xl font-semibold">
      <Image 
        src={logoUrl}
        style={{objectFit: "contain"}} 
        alt="royal bird studio"
        width={120}
        height={40}
      />
     <div className="flex items-center justify-around gap-5">
          <Button variant="outline">LOG IN</Button>
      </div>
    </nav>
  )
}

function BottomNav() {
  const router = useRouter();
  const pathname = usePathname();

  const navItems = [
    { 
      icon: Home, 
      label: 'Home', 
      path: '/',
      active: pathname === '/'
    },
    { 
      icon: BookOpen, 
      label: 'Comics', 
      path: '/comics',
      active: pathname === '/comics' || pathname.startsWith('/comics/')
    },
    // { 
    //   icon: Search, 
    //   label: 'Discover', 
    //   path: '/discover',
    //   active: pathname === '/discover'
    // },
    { 
      icon: Newspaper, 
      label: 'Blog', 
      path: '/blog',
      active: pathname === '/blog'
    },
    { 
      icon: User, 
      label: 'About Us', 
      path: '/about',
      active: pathname === '/about'
    }
  ];

  const handleNavigation = (path: string) => {
    router.push(path);
  };

  return (
    <nav className="fixed bottom-6 left-1/2 transform -translate-x-1/2 flex items-center justify-between w-fit bg-white/95 backdrop-blur-md rounded-full p-3 text-xl font-semibold shadow-2xl border border-gray-300/50 z-50">
      <div className="flex items-center justify-around gap-3">
        {navItems.map((item) => {
          const Icon = item.icon;
          return (
            <button
              key={item.path}
              onClick={() => handleNavigation(item.path)}
              className={`relative p-3 rounded-full transition-all duration-300 group ${
                item.active 
                  ? 'bg-gradient-to-r from-purple-600 to-pink-600 text-white shadow-lg transform scale-105' 
                  : 'hover:bg-gray-100 text-gray-600 hover:text-gray-900'
              }`}
              aria-label={item.label}
            >
              <Icon 
                size={22} 
                className={`transition-transform duration-300 ${
                  item.active ? 'scale-110' : 'group-hover:scale-105'
                }`} 
              />
              
              {/* Active indicator dot */}
              {item.active && (
                <div className="absolute -top-1 -right-1 w-2 h-2 bg-white rounded-full border-2 border-purple-600" />
              )}
              
              {/* Tooltip */}
              <div className="absolute -top-12 left-1/2 transform -translate-x-1/2 bg-gray-900 text-white text-xs font-medium px-2 py-1 rounded-md opacity-0 group-hover:opacity-100 transition-opacity duration-300 whitespace-nowrap pointer-events-none">
                {item.label}
                <div className="absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-1 w-2 h-2 bg-gray-900 rotate-45" />
              </div>
            </button>
          );
        })}
      </div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="flex flex-col gap-4">
        {/* <TopNav /> */}
        <BottomNav />
        {children}
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
