"use client"
import "~/styles/globals.css";

import { type Metadata } from "next";
import { Bangers, Chewy, Comic_Neue, Geist, Inter, Montserrat } from "next/font/google";
import Footer from "~/components/footer";
import BottomNav from "~/components/ui/bottomNav";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-montserrat",
});

const chewy = Chewy({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-chewy",
})

const comicNeue = Comic_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-comic-neue",
});

const bangers = Bangers({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bangers",
});

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${chewy.className}`}>
      <body className="flex flex-col gap-4">
        {/* <TopNav /> */}
        <BottomNav />
        {children}
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
